#### Tensor 이해 - 생성
- Tensor란? 
    * pytorch에서 데이터를 저장하는 객체
    * 모델에 입력/출력 데이터 형태

데이터타입 변수명 = 데이터
int age = 10

기본 데이터 타입 => 숫자, 글자 ==> int, float, char, bool 
- C/C+++/C#/JAVA ==> 스택
- python => 힙(클래스기반 객체)

확장 데이터 타입 => 여러 개의 기본 데이터 타입 모여서 하나의 데이터 표현 [string]
C => 구조체
Java 외 OOP => 구조체 + 함수 => 클래스
- C/C++/C#/JAVA/Python ==> 힙(클래스기반 객체)

- 정수 int ==> 크기 다양
* byte => 8비트 => 256개 => int8/unit8

- 부호(-/+) : -128 ~ 0 ~ 127  : -2^7 ~ 2^7 -1
- 부호 X    : 0 ~ 255 ==> (이미지데이터 픽셀 색상값)
* short => 16비트 ==> -2^15 ~ + 2^15-1 ==>int16/unit16
* int => 32비트 ==> int32/unit32  -2^31 ~ 2^31 -1
* long int => 64비트 ==> int64/unit64  -2^63 ~ 2^63 -1

- 실수 3.12 ====> 정수부 3, 실수부 12
- 실수 float => 소수점 이하 자릿수
* float => 7/8                  4바이트 int32
* double => float 소수점 2배     8바이트 double

In [4]:
import torch

print(f'torch v.{torch.__version__}')

torch v.2.4.1


In [2]:
def printInfo(obj, obj_name):
    print(f'\n[{obj_name}]')
    print(f'shape : {obj.shape}')
    print(f'ndim : {obj.ndim}차원')
    print(f'dtype : {obj.dtype}')
    print(f'device : {obj.device}')
    print(f'data :\n{obj.data}')

- 텐서 생성 [1] torch.tensor()

In [3]:
# 생성 형식 : torch.tensor(데이터)
ten1=torch.tensor(10)
ten2=torch.tensor([22,33,44])
ten3=torch.tensor([[90,91], [80,81], [70,71]])

# 텐서 정보 출력
printInfo(ten1, 'ten1')
printInfo(ten2, 'ten2')
printInfo(ten3, 'ten3')


[ten1]
shape : torch.Size([])
ndim : 0차원
dtype : torch.int64
device : cpu
data :
10

[ten2]
shape : torch.Size([3])
ndim : 1차원
dtype : torch.int64
device : cpu
data :
tensor([22, 33, 44])

[ten3]
shape : torch.Size([3, 2])
ndim : 2차원
dtype : torch.int64
device : cpu
data :
tensor([[90, 91],
        [80, 81],
        [70, 71]])


In [8]:
## 데이터 1개 즉, 스칼라
dataTF=torch.tensor(10)
printInfo(dataTF, 'dataTF')

dataTF=torch.tensor(10, dtype=torch.uint8) 
printInfo(dataTF, 'dataTF')


[dataTF]
shape : torch.Size([])
ndim : 0차원
dtype : torch.int64
device : cpu
data :
10

[dataTF]
shape : torch.Size([])
ndim : 0차원
dtype : torch.uint8
device : cpu
data :
10


In [9]:
## 데이터 1개 즉, 벡터 1D
dataTF=torch.tensor([10])
printInfo(dataTF, 'dataTF')

dataTF=torch.tensor([10], dtype=torch.uint8) 
printInfo(dataTF, 'dataTF')


[dataTF]
shape : torch.Size([1])
ndim : 1차원
dtype : torch.int64
device : cpu
data :
tensor([10])

[dataTF]
shape : torch.Size([1])
ndim : 1차원
dtype : torch.uint8
device : cpu
data :
tensor([10], dtype=torch.uint8)


In [10]:
## 데이터 1개 즉, 행렬 2D
dataTF=torch.tensor([[10]])
printInfo(dataTF, 'dataTF')

dataTF=torch.tensor([[10],[20]], dtype=torch.uint8) 
printInfo(dataTF, 'dataTF')


[dataTF]
shape : torch.Size([1, 1])
ndim : 2차원
dtype : torch.int64
device : cpu
data :
tensor([[10]])

[dataTF]
shape : torch.Size([2, 1])
ndim : 2차원
dtype : torch.uint8
device : cpu
data :
tensor([[10],
        [20]], dtype=torch.uint8)


In [12]:
## 데이터 1개 즉, 행렬 ND
dataTF=torch.tensor([[[10]]])
printInfo(dataTF, 'dataTF')

dataTF=torch.tensor([[[[10],[20]]]], dtype=torch.uint8) 
printInfo(dataTF, 'dataTF')


[dataTF]
shape : torch.Size([1, 1, 1])
ndim : 3차원
dtype : torch.int64
device : cpu
data :
tensor([[[10]]])

[dataTF]
shape : torch.Size([1, 1, 2, 1])
ndim : 4차원
dtype : torch.uint8
device : cpu
data :
tensor([[[[10],
          [20]]]], dtype=torch.uint8)
