Tensor 이해

In [1]:
### 모듈 로딩
import torch

- Tensor 생성 [2] torch.rand()

In [8]:
# 0 <= ~ < 1 범위의 임의의 숫자를 1개 추출 => rand(*size)
# rand(*size) : 가변인자 ==> 몇 차원인지 알 수 없음!
torch.manual_seed(1)

dataTS1=torch.rand(3)       #1D Vector
dataTS2=torch.rand(2,3)     #2D Matrix
dataTS3=torch.rand(2,2,3)   #3D 3D Tensor


In [11]:
print(dataTS1, dataTS2, dataTS3, sep='\n')

tensor([0.7576, 0.2793, 0.4031])
tensor([[0.7347, 0.0293, 0.7999],
        [0.3971, 0.7544, 0.5695]])
tensor([[[0.4388, 0.6387, 0.5247],
         [0.6826, 0.3051, 0.4635]],

        [[0.4550, 0.5725, 0.4980],
         [0.9371, 0.6556, 0.3138]]])


- Tensor 생성 [3] torch.randn()

In [14]:
dataTS1=torch.randn(3)       #1D Vector
dataTS2=torch.randn(2,3)     #2D Matrix
dataTS3=torch.randn(2,1,3)   #3D 3D Tensor

print(dataTS1, dataTS2, dataTS3, sep='\n')

tensor([-0.5581, -0.3964,  1.4130])
tensor([[-2.6119, -1.6396,  2.3906],
        [-0.5024,  0.0476, -1.1322]])
tensor([[[-0.0179,  0.1280, -0.5552]],

        [[-0.4575, -1.9599, -1.1242]]])


- Tensor 생성 [4] torch.randint()

In [17]:
torch.randint(1,46,(4,6))

tensor([[44, 38, 11,  1, 45, 22],
        [45, 35, 25, 21, 32, 25],
        [ 2, 36, 33, 33, 13, 14],
        [ 4, 19, 36, 40, 44, 15]])